sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc
  - sudo apt-get install -y g++
  - sudo apt-get install -y libprotobuf-dev
  - sudo apt-get install -y protobuf-compiler
  - sudo apt-get install -y cmake
  - sudo apt-get install -y python
  - sudo apt-get install -y bc
  - sudo apt-get install -y kmod

script:
  - ./configure --no-kernel
  - make usr
  - sudo make usr_install
  - uname -a
  - ls -l /lib/modules || true
